server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://jayeshmanohare2003_db_user:pJ7WnxtXzl27mbJJ@clusterjayesh.8gttef3.mongodb.net/Clusterjayesh?appName=Clusterjayesh

logging:
  level:
    in.cloudblitz.course: DEBUG
