server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://jayeshmanohare2003_db_user:oknWcHhfJkfnwBhk@clusterdatabase.xtrzpnr.mongodb.net/?appName=Clusterdatabase

logging:
  level:
    in.cloudblitz.course: DEBUG
