server:
  port: 8082

spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://jayeshmanohare2003_db_user:oknWcHhfJkfnwBhk@clusterdatabase.xtrzpnr.mongodb.net/Clusterdatabase?appName=Clusterdatabase

logging:
  level:
    in.cloudblitz.course: DEBUG
