server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://jayeshmanohare2003_db_user:pJ7WnxtXzl27mbJJ@clusterjayesh.8gttef3.mongodb.net/?appName=Clusterjayesh

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:CloudBlitzJWTSecretKeyForSecureAuthentication2024!@#}
  expiration: 86400000 # 24 hours

logging:
  level:
    in.cloudblitz.auth: DEBUG
